### ISSUE TITLE
Clean UP & Dockerization of eos8ioa

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos8ioa#1]

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

Please provide updates when you have them. Is this model working?

**Comment by samuelmaina** [comment]
@GemmaTuron I have refactor the model and changed the all the necessary files. The dependances are the problem. There is only one dependency for the model rdkit=2021.03.01. I have been trying different version for the rdkit but none is downloading. It's  always resolving environment.I have tried creating local env to try to run.sh but I can't figure it out.
For the docker images, the workflows  are always failing on our side due to lack of env variables .The workflows are called after you approve a PR making it hard for testing.I am still looking for solutions for that through mimicking the situation.

**Comment by GemmaTuron** [comment]
Please attach the log files so we can see what is happening.
Do not attempt to run workflows until the model works successfully on your system with the --repo_path option

**Comment by samuelmaina** [comment]
Sorry, I was referring to different issues , this model refactoring and the newly assigned docker issue. I have not run eos8ioa with the github actions. I have tried to run the  model with  --repo_path  but the  process is always stuck for long at this logs 
```08:35:36 | DEBUG    | conda install -c conda-forge rdkit -y
python -m pip --disable-pip-version-check install git+https://github.com/ersilia-os/bentoml-ersilia.git

08:35:38 | DEBUG    | Activating base environment
08:35:38 | DEBUG    | Current working directory: /home/samuelmayna/eos/dest/eos8ioa
08:35:38 | DEBUG    | Running bash /tmp/ersilia-yjxz3bnf/script.sh > /tmp/ersilia-2sohb44g/command_outputs.log 2>&1
08:38:03 | DEBUG    | # conda environments:
#
base                     /home/samuelmayna/miniconda3
eos8ioa               *  /home/samuelmayna/miniconda3/envs/eos8ioa
eosbase-bentoml-0.11.0-py37     /home/samuelmayna/miniconda3/envs/eosbase-bentoml-0.11.0-py37
ersilia                  /home/samuelmayna/miniconda3/envs/ersilia

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... failed
```
It then fails with 'rdkit not found'
inspecting `tmp/ersilia-2sohb44g/command_outputs.log `, conda is frozen with `Solving environment: ...working... unsuccessful initial attempt using frozen solve. Retrying with flexible solve.`
I created a separate env for eos8ioa  with only python 3.7 in it and I get try installing it  rdkit 2021.03 but conda is just resolving. I am trying to look for something that can work. I am trying all the conda modules but if they fail I will just use pip

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 
Can you try a pip installable version of rdkit?
The best is to manually create the environment and install the packages one by one first, and then try to run the `run.sh` file manually -- after all this is successful, run the model inside ersilia

**Comment by samuelmaina** [comment]
Hi @GemmaTuron , 
I have refactored the model and  its working. I  am getting this error when pushing, `batch response: @samuelmaina can not upload new objects to public fork samuelmaina/eos8ioa`, which I guess means the Git LFS quota is depleted.

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

The Git LFS quota on our side is fine, there is still plenty of GB. It is probably because Git LFS was not initialized in the repo originally, Is there any file that requires Git LFS? If there isn't, just avoid any tracking and try to push again

**Comment by samuelmaina** [comment]
The model is 2MB. I will just push it without LFS

**Comment by samuelmaina** [comment]
Hi @GemmaTuron,
I raised a PR for this model, can you review it?

**Comment by GemmaTuron** [comment]
Thanks @samuelmaina !

The model has passed all the checks and uploaded to S3 and DockerHub. Let's see if the testing also works in #3 !
